(function () {
  'use strict';
  if (localStorage.getItem('isLoggedIn') !== 'true') { window.location.href = 'login.html'; return; }
  var view = new URLSearchParams(window.location.search).get('view') || 'projects';
  var content = document.getElementById('sectionContent');
  var data = {
    projects: {k:'WORKSPACE / PROJECTS',t:'Project Library',d:'Organize every product story, milestone and delivery from one focused workspace.',img:'images/project-dashboard.svg',cards:'<div class="section-card"><h3>Active Projects</h3><span class="section-number">12</span><span class="section-meta">4 due this month</span></div><div class="section-card"><h3>Completion Rate</h3><span class="section-number">86%</span><span class="section-meta">Up 12% this quarter</span></div><div class="section-card"><h3>New Brief</h3><p>Capture a new design opportunity.</p><button class="section-button">Add Project</button></div>',body:'<div class="section-card section-wide"><h3>Recent project pipeline</h3><ul class="section-list"><li><strong>FinTech Banking App</strong><span>Completed</span></li><li><strong>E-commerce Redesign</strong><span>In progress</span></li><li><strong>Healthcare Platform</strong><span>Review</span></li><li><strong>Travel Portal</strong><span>Planning</span></li></ul></div><div class="section-card"><h3>Project mix</h3><div class="pie-chart"></div><span class="section-meta">Mobile 42% · Web 28% · SaaS 16%</span></div>'},
    'case-studies': {k:'WORKSPACE / CASE STUDIES',t:'Case Study Studio',d:'Turn process into persuasive stories with research, decisions and measurable outcomes.',img:'images/project-fintech.svg',cards:'<div class="section-card"><h3>Published Stories</h3><span class="section-number">18</span><span class="section-meta">3 awaiting review</span></div><div class="section-card"><h3>Reader Engagement</h3><span class="section-number">72%</span><span class="section-meta">Average completion</span></div><div class="section-card"><h3>Featured story</h3><p>FinTech Banking App</p><button class="section-button">Open Story</button></div>',body:'<div class="section-card section-wide"><img class="section-image" src="images/project-fintech.svg" alt="FinTech case study"><h3>FinTech Banking App</h3><p>Research-led redesign that simplified payments and improved task confidence.</p><button class="section-button">Edit Case Study</button></div><div class="section-card"><h3>Story status</h3><div class="bar-set"><i style="--h:80%"></i><i style="--h:55%"></i><i style="--h:92%"></i><i style="--h:68%"></i></div><span class="section-meta">Research · Flow · UI · Results</span></div>'},
    clients: {k:'WORKSPACE / CLIENTS',t:'Client Relationships',d:'Keep conversations, project health and next actions visible for every partnership.',img:'images/profile-placeholder.svg',cards:'<div class="section-card"><h3>Active Clients</h3><span class="section-number">24</span><span class="section-meta">6 new this month</span></div><div class="section-card"><h3>Retention</h3><span class="section-number">94%</span><span class="section-meta">Excellent health</span></div><div class="section-card"><h3>Average NPS</h3><span class="section-number">68</span><span class="section-meta">+8 from last quarter</span></div>',body:'<div class="section-card section-wide"><h3>Client health</h3><ul class="section-list"><li><strong>FinBank Corp</strong><span>Healthy · 92%</span></li><li><strong>ShopNow Inc</strong><span>Healthy · 86%</span></li><li><strong>MedCare Ltd</strong><span>Needs attention · 61%</span></li><li><strong>QuickBite</strong><span>Healthy · 89%</span></li></ul></div><div class="section-card"><h3>Add a client</h3><form class="section-form"><label>Company<input placeholder="Company name"></label><br><label>Contact email<input type="email" placeholder="name@company.com"></label><br><button class="section-button">Save Client</button></form></div>'},
    messages: {k:'WORKSPACE / MESSAGES',t:'Message Center',d:'Reply to project questions and keep important decisions close to the work.',img:'images/project-ecommerce.svg',cards:'<div class="section-card"><h3>Unread</h3><span class="section-number">04</span><span class="section-meta">2 high priority</span></div><div class="section-card"><h3>Response time</h3><span class="section-number">2.4h</span><span class="section-meta">Within your target</span></div><div class="section-card"><h3>Open threads</h3><span class="section-number">16</span><span class="section-meta">Across 8 clients</span></div>',body:'<div class="section-card section-wide"><h3>Recent conversations</h3><ul class="section-list"><li><strong>Sarah · FinBank</strong><span>Updated payment flow</span></li><li><strong>Mark · ShopNow</strong><span>Homepage feedback</span></li><li><strong>Priya · MedCare</strong><span>Research interview dates</span></li></ul></div><div class="section-card"><h3>Quick reply</h3><form class="section-form"><label>To<input placeholder="Client name"></label><br><label>Message<textarea placeholder="Write a thoughtful reply..."></textarea></label><button class="section-button">Send Message</button></form></div>'},
    analytics: {k:'WORKSPACE / ANALYTICS',t:'Design Analytics',d:'See how your work performs with clear signals for reach, engagement and conversion.',img:'images/project-healthcare.svg',cards:'<div class="section-card"><h3>Portfolio Views</h3><span class="section-number">24.8K</span><span class="section-meta">+18.4% this month</span></div><div class="section-card"><h3>Enquiries</h3><span class="section-number">148</span><span class="section-meta">+22 new leads</span></div><div class="section-card"><h3>Conversion</h3><span class="section-number">6.2%</span><span class="section-meta">Above industry average</span></div>',body:'<div class="section-card section-wide"><h3>Monthly performance</h3><div class="bar-set"><i style="--h:38%"></i><i style="--h:56%"></i><i style="--h:48%"></i><i style="--h:72%"></i><i style="--h:64%"></i><i style="--h:90%"></i></div><span class="section-meta">Jan · Feb · Mar · Apr · May · Jun</span></div><div class="section-card"><h3>Traffic sources</h3><div class="pie-chart"></div><span class="section-meta">Search 42% · Social 28% · Direct 30%</span></div>'},
    profile: {k:'WORKSPACE / PROFILE',t:'Your Creative Profile',d:'Shape how clients see your expertise, strengths and availability.',img:'images/profile-placeholder.svg',cards:'<div class="section-card"><h3>Profile strength</h3><span class="section-number">92%</span><span class="section-meta">Almost complete</span></div><div class="section-card"><h3>Profile views</h3><span class="section-number">1,284</span><span class="section-meta">This month</span></div><div class="section-card"><h3>Availability</h3><span class="section-number">Open</span><span class="section-meta">For 2 new projects</span></div>',body:'<div class="section-card section-wide"><h3>Update your details</h3><form class="section-form form-grid"><label>Name<input value="Stackly Designer"></label><label>Role<input value="UI/UX Designer"></label><label class="full">Bio<textarea>Product designer focused on clear, useful and memorable digital experiences.</textarea></label><label>Location<input value="Bangalore, India"></label><label>Website<input placeholder="https://yourportfolio.com"></label><div class="full"><button class="section-button">Save Profile</button></div></form></div><div class="section-card"><img class="section-image" src="images/profile-placeholder.svg" alt="Profile preview"><h3>Public profile</h3><p>Visible to clients and collaborators.</p></div>'},
    settings: {k:'WORKSPACE / SETTINGS',t:'Workspace Settings',d:'Control preferences, notifications and the way your Stackly workspace behaves.',img:'images/Stackly_logo.png',cards:'<div class="section-card"><h3>Theme</h3><span class="section-number">Dark</span><span class="section-meta">Easy on the eyes</span></div><div class="section-card"><h3>Notifications</h3><span class="section-number">On</span><span class="section-meta">Email and browser alerts</span></div><div class="section-card"><h3>Security</h3><span class="section-number">Good</span><span class="section-meta">Last checked today</span></div>',body:'<div class="section-card section-wide"><h3>Preferences</h3><form class="section-form form-grid"><label>Workspace name<input value="Stackly Design Studio"></label><label>Timezone<select><option>Asia / Kolkata</option><option>UTC</option></select></label><label><span>Email notifications</span><input type="checkbox" checked></label><label><span>Weekly summary</span><input type="checkbox" checked></label><div class="full"><button class="section-button">Save Settings</button></div></form></div><div class="section-card"><img class="section-image" src="images/Stackly_logo.png" alt="Stackly settings"><h3>Stackly workspace</h3><p>Your personal command center for design work.</p></div>'}
  };
  var item = data[view] || data.projects;
  var latestUpdates = {
    projects: ['Pipeline refreshed', 'Two active projects moved to client review.', 'Updated 1 hour ago · 2 reviews pending'],
    'case-studies': ['Story review complete', 'The FinTech case study is ready for publishing.', 'Updated 2 hours ago · Ready to publish'],
    clients: ['Client health check', 'MedCare Ltd requested a follow-up design review.', 'Updated 3 hours ago · Follow-up needed'],
    messages: ['Inbox organized', 'Four conversations are waiting for a response.', 'Updated 30 minutes ago · 2 high priority'],
    analytics: ['Monthly insight', 'Portfolio enquiries increased by 18.4% this month.', 'Updated today · Above target'],
    profile: ['Profile refreshed', 'Your creative profile is now 92% complete.', 'Updated yesterday · Almost complete'],
    settings: ['Workspace synced', 'Notification and timezone preferences are up to date.', 'Updated today · All settings saved']
  };
  var latest = latestUpdates[view] || latestUpdates.projects;
  var sharedTools = '<div class="section-card"><h3>Section overview</h3><div class="pie-chart"></div><span class="section-meta">Progress 68% · Goal tracking active</span></div><div class="section-card"><h3>Latest update</h3><p><strong>'+latest[0]+'</strong></p><p>'+latest[1]+'</p><span class="section-meta">'+latest[2]+'</span></div>';
  content.innerHTML = '<section class="section-hero"><div><span class="section-kicker">'+item.k+'</span><h1 class="section-title">'+item.t+'</h1><p class="section-description">'+item.d+'</p></div><img class="section-hero-art" src="'+item.img+'" alt="'+item.t+' visual"></section><section class="section-grid">'+item.cards+'</section><section class="section-grid">'+item.body+sharedTools+'</section>';
  document.querySelectorAll('.sidebar-nav .nav-item').forEach(function (navItem) {
    var first = navItem.firstChild;
    if (first && first.nodeType === 3 && first.textContent.trim()) {
      var icon = document.createElement('span');
      icon.className = 'nav-icon nav-symbol';
      icon.textContent = first.textContent.trim();
      navItem.replaceChild(icon, first);
    }
  });
  document.querySelectorAll('[data-view="'+view+'"]').forEach(function (el) { el.classList.add('active'); });
  document.getElementById('logoutBtn').addEventListener('click', function () { if (window.confirm('Are you sure you want to log out?')) { localStorage.removeItem('isLoggedIn'); window.location.href = 'login.html'; } });
  document.getElementById('menuBtn').addEventListener('click', function () { document.getElementById('sidebar').classList.toggle('open'); });
}());
